-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-10-05 16:24:44 EDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE jc_dept (
    deptno  NUMBER(2) NOT NULL,
    dname   VARCHAR2(30) NOT NULL,
    loc     VARCHAR2(30) NOT NULL,
    dept_id NUMBER NOT NULL
);

COMMENT ON COLUMN jc_dept.deptno IS
    'Department ID Number';

COMMENT ON COLUMN jc_dept.dname IS
    'Department Name';

COMMENT ON COLUMN jc_dept.loc IS
    'Location City of the Department';

ALTER TABLE jc_dept ADD CONSTRAINT dept_pk PRIMARY KEY ( deptno );

CREATE TABLE jc_emp (
    empno    NUMBER(4) NOT NULL,
    efname   VARCHAR2(30) NOT NULL,
    elname   VARCHAR2(30) NOT NULL,
    job      VARCHAR2(30) NOT NULL,
    mgr      NUMBER(4),
    hiredate DATE NOT NULL,
    sal      NUMBER(7, 2) NOT NULL,
    comm     NUMBER(7, 2),
    deptno   NUMBER(2) NOT NULL
);

COMMENT ON COLUMN jc_emp.empno IS
    'Employee ID Number';

COMMENT ON COLUMN jc_emp.efname IS
    'Employee First Name';

COMMENT ON COLUMN jc_emp.elname IS
    'Employee Last Name';

COMMENT ON COLUMN jc_emp.job IS
    'Employee Functional Role';

COMMENT ON COLUMN jc_emp.mgr IS
    'Employee Manager ID';

COMMENT ON COLUMN jc_emp.hiredate IS
    'Empoyee Join Date';

COMMENT ON COLUMN jc_emp.sal IS
    'Employee Monthly Salary in USD';

COMMENT ON COLUMN jc_emp.comm IS
    'Employee Commission';

ALTER TABLE jc_emp ADD CONSTRAINT emp_pk PRIMARY KEY ( empno );

CREATE TABLE jc_emp_project (
    hours  NUMBER(4) NOT NULL,
    empno  NUMBER(4) NOT NULL,
    projno NUMBER(3) NOT NULL
);

ALTER TABLE jc_emp_project ADD CONSTRAINT emp_project_pk PRIMARY KEY ( projno,
                                                                       empno );

CREATE TABLE jc_project (
    projno    NUMBER(3) NOT NULL,
    pname     VARCHAR2(30) NOT NULL,
    startdate DATE NOT NULL,
    enddate   DATE NOT NULL
);

COMMENT ON COLUMN jc_project.projno IS
    'Project Number';

COMMENT ON COLUMN jc_project.pname IS
    'Name of the Project';

COMMENT ON COLUMN jc_project.startdate IS
    'Start Date of the Project';

COMMENT ON COLUMN jc_project.enddate IS
    'End Date of the Project';

ALTER TABLE jc_project ADD CONSTRAINT project_pk PRIMARY KEY ( projno );

CREATE TABLE jc_salgrade (
    grade VARCHAR2(2) NOT NULL,
    hisal NUMBER(7, 2) NOT NULL,
    losal NUMBER(7, 2) NOT NULL
);

COMMENT ON COLUMN jc_salgrade.grade IS
    'Salary Grade of Employee';

COMMENT ON COLUMN jc_salgrade.hisal IS
    'High Salary Value';

COMMENT ON COLUMN jc_salgrade.losal IS
    'Low Salary Value';

ALTER TABLE jc_salgrade ADD CONSTRAINT salgrade_pk PRIMARY KEY ( grade );

ALTER TABLE jc_emp
    ADD CONSTRAINT emp_dept_fk FOREIGN KEY ( deptno )
        REFERENCES jc_dept ( deptno );

ALTER TABLE jc_emp
    ADD CONSTRAINT emp_emp_fk FOREIGN KEY ( mgr )
        REFERENCES jc_emp ( empno );

ALTER TABLE jc_emp_project
    ADD CONSTRAINT emp_project_emp_fk FOREIGN KEY ( empno )
        REFERENCES jc_emp ( empno );

ALTER TABLE jc_emp_project
    ADD CONSTRAINT emp_project_project_fk FOREIGN KEY ( projno )
        REFERENCES jc_project ( projno );

CREATE SEQUENCE jc_dept_dept_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER jc_dept_dept_id_trg BEFORE
    INSERT ON jc_dept
    FOR EACH ROW
    WHEN ( new.dept_id IS NULL )
BEGIN
    :new.dept_id := jc_dept_dept_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
