-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-10-12 01:50:31 EDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE jc_facility (
    jc_facility_id       NUMBER(4)
        CONSTRAINT nnc_jc_facility_facilityid NOT NULL,
    elevator             CHAR(1),
    escalator            CHAR(1),
    restroom             CHAR(1),
    wheelchairaccessible CHAR(1),
    transferconnection   CHAR(1),
    busconnection        CHAR(1),
    twentyfourhourbooth  CHAR(1),
    jc_station_id        NUMBER(4)
);

COMMENT ON TABLE jc_facility IS
    'FacilityID
';

ALTER TABLE jc_facility ADD CONSTRAINT jc_facility_pk PRIMARY KEY ( jc_facility_id );

CREATE TABLE jc_operation (
    jc_operation_id              NUMBER(4) NOT NULL,
    arrivaldatetime              DATE NOT NULL,
    departuredatetime            DATE NOT NULL,
    localexpressmixed            VARCHAR2(30) NOT NULL,
    jc_station_jc_station_id     NUMBER(4)
        CONSTRAINT nnc_jc_operation_jc_station_id NOT NULL,
    jc_trainline_jc_trainline_id NUMBER(4) NOT NULL
);

COMMENT ON TABLE jc_operation IS
    'OperationID';

ALTER TABLE jc_operation ADD CONSTRAINT jc_operation_pk PRIMARY KEY ( jc_operation_id );

CREATE TABLE jc_station (
    jc_station_id                NUMBER(4)
        CONSTRAINT nnc_jc_station_jc_station_id NOT NULL,
    stationname                  VARCHAR2(30)
        CONSTRAINT nnc_jc_station_stationname NOT NULL,
    stationaddress               VARCHAR2(30)
        CONSTRAINT nnc_jc_station_stationaddress NOT NULL,
    borough                      VARCHAR2(30)
        CONSTRAINT nnc_jc_station_borough NOT NULL,
    neighborhood                 VARCHAR2(30)
        CONSTRAINT nnc_jc_station_neighborhood NOT NULL,
    jc_trainline_jc_trainline_id NUMBER(4)
        CONSTRAINT nnc_jc_station_jc_trainline_id NOT NULL
);

COMMENT ON TABLE jc_station IS
    'StationID';

ALTER TABLE jc_station ADD CONSTRAINT jc_station_pk PRIMARY KEY ( jc_station_id );

CREATE TABLE jc_trainline (
    jc_trainline_id  NUMBER(4) NOT NULL,
    linename         VARCHAR2(30)
        CONSTRAINT nnc_jc_trainline_linename NOT NULL,
    division         VARCHAR2(30)
        CONSTRAINT nnc_jc_trainline_division NOT NULL,
    yearsinoperation NUMBER(4) NOT NULL
);

COMMENT ON TABLE jc_trainline IS
    'TrainID';

ALTER TABLE jc_trainline ADD CONSTRAINT jc_trainline_pk PRIMARY KEY ( jc_trainline_id );

ALTER TABLE jc_facility
    ADD CONSTRAINT jc_facility_jc_station_fk FOREIGN KEY ( jc_station_id )
        REFERENCES jc_station ( jc_station_id );

ALTER TABLE jc_operation
    ADD CONSTRAINT jc_operation_jc_station_fk FOREIGN KEY ( jc_station_jc_station_id )
        REFERENCES jc_station ( jc_station_id );

ALTER TABLE jc_operation
    ADD CONSTRAINT jc_operation_jc_trainline_fk FOREIGN KEY ( jc_trainline_jc_trainline_id )
        REFERENCES jc_trainline ( jc_trainline_id );

ALTER TABLE jc_station
    ADD CONSTRAINT jc_station_jc_trainline_fk FOREIGN KEY ( jc_trainline_jc_trainline_id )
        REFERENCES jc_trainline ( jc_trainline_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              8
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
