-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-10-12 16:36:55 EDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE jc_courier (
    jc_courier_id        VARCHAR2(20)
        CONSTRAINT nnc_jc_courier_phone_number NOT NULL,
    name                 VARCHAR2(50)
        CONSTRAINT nnc_jc_courier_name NOT NULL,
    age                  INTEGER
        CONSTRAINT nnc_jc_courier_age NOT NULL,
    home_address         VARCHAR2(100)
        CONSTRAINT nnc_jc_courier_home_address NOT NULL,
    vehicle_type         VARCHAR2(20)
        CONSTRAINT nnc_jc_courier_vehicle_type NOT NULL,
    vehicle_plate_number VARCHAR2(20),
    gender               CHAR(1)
        CONSTRAINT nnc_jc_courier_gender NOT NULL,
    bank_account_number  VARCHAR2(20) NOT NULL,
    bank_routing_number  VARCHAR2(20) NOT NULL
);

COMMENT ON TABLE jc_courier IS
    'Courier';

ALTER TABLE jc_courier ADD CONSTRAINT jc_courier_pk PRIMARY KEY ( jc_courier_id );

CREATE TABLE jc_customer (
    jc_customer_id VARCHAR2(20)
        CONSTRAINT nnc_jc_customer_phone_number NOT NULL,
    name           VARCHAR2(50)
        CONSTRAINT nnc_jc_customer_name NOT NULL,
    age            INTEGER
        CONSTRAINT nnc_jc_customer_age NOT NULL,
    home_address   VARCHAR2(100)
        CONSTRAINT nnc_jc_customer_home_address NOT NULL,
    email_address  VARCHAR2(100)
        CONSTRAINT nnc_jc_customer_email_address NOT NULL,
    customer_type  VARCHAR2(20)
        CONSTRAINT nnc_jc_customer_customer_type NOT NULL
);

COMMENT ON TABLE jc_customer IS
    'Customer';

ALTER TABLE jc_customer ADD CONSTRAINT jc_customer_pk PRIMARY KEY ( jc_customer_id );

CREATE TABLE jc_orders (
    jc_orders_id             INTEGER
        CONSTRAINT nnc_jc_orders_order_id NOT NULL,
    date_time_order          TIMESTAMP
        CONSTRAINT nnc_jc_orders_date_time_order NOT NULL,
    date_time_delivery       TIMESTAMP NOT NULL,
    order_amount             NUMBER(10, 2)
        CONSTRAINT nnc_jc_orders_order_amount NOT NULL,
    tips                     NUMBER(10, 2)
        CONSTRAINT nnc_jc_orders_tips NOT NULL,
    payment_method           VARCHAR2(20)
        CONSTRAINT nnc_jc_orders_payment_method NOT NULL,
    card_number              VARCHAR2(16)
        CONSTRAINT nnc_jc_orders_card_number NOT NULL,
    name_on_card             VARCHAR2(50)
        CONSTRAINT nnc_jc_orders_name_on_card NOT NULL,
    expiration_date          DATE
        CONSTRAINT nnc_jc_orders_expiration_date NOT NULL,
    cvv_number               VARCHAR2(4)
        CONSTRAINT nnc_jc_orders_cvv_number NOT NULL,
    jc_customer_phone_number VARCHAR2(20),
    jc_courier_phone_number  VARCHAR2(20),
    jc_restaurant_name       VARCHAR2(100)
);

COMMENT ON TABLE jc_orders IS
    'Orders';

ALTER TABLE jc_orders ADD CONSTRAINT jc_orders_pk PRIMARY KEY ( jc_orders_id );

CREATE TABLE jc_restaurant (
    jc_restaurant_id VARCHAR2(100)
        CONSTRAINT nnc_jc_restaurant_name NOT NULL,
    address          VARCHAR2(100)
        CONSTRAINT nnc_jc_restaurant_address NOT NULL,
    phone_number     VARCHAR2(20)
        CONSTRAINT nnc_jc_restaurant_phone_number NOT NULL,
    website_url      VARCHAR2(100),
    specialty        VARCHAR2(100)
        CONSTRAINT nnc_jc_restaurant_specialty NOT NULL
);

COMMENT ON TABLE jc_restaurant IS
    'Restaurant';

ALTER TABLE jc_restaurant ADD CONSTRAINT jc_restaurant_pk PRIMARY KEY ( jc_restaurant_id );

ALTER TABLE jc_orders
    ADD CONSTRAINT jc_orders_jc_courier_fk FOREIGN KEY ( jc_courier_phone_number )
        REFERENCES jc_courier ( jc_courier_id );

ALTER TABLE jc_orders
    ADD CONSTRAINT jc_orders_jc_customer_fk FOREIGN KEY ( jc_customer_phone_number )
        REFERENCES jc_customer ( jc_customer_id );

ALTER TABLE jc_orders
    ADD CONSTRAINT jc_orders_jc_restaurant_fk FOREIGN KEY ( jc_restaurant_name )
        REFERENCES jc_restaurant ( jc_restaurant_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
