-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-10-22 15:17:47 EDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE jc_cust_order (
    order_quality NUMBER(5) NOT NULL,
    prod_id       NUMBER(5) NOT NULL,
    order_id      NUMBER(4) NOT NULL
);

CREATE TABLE jc_customer (
    cust_id      NUMBER(6) NOT NULL,
    cust_fname   VARCHAR2(30) NOT NULL,
    cust_lname   VARCHAR2(30) NOT NULL,
    cust_str     VARCHAR2(30) NOT NULL,
    cust_city    VARCHAR2(20) NOT NULL,
    cust_state   VARCHAR2(30) NOT NULL,
    cust_zipcode VARCHAR2(10) NOT NULL
);

ALTER TABLE jc_customer ADD CONSTRAINT jc_customer_pk PRIMARY KEY ( cust_id );

CREATE TABLE jc_invoice (
    invoice_id NUMBER(5) NOT NULL,
    order_id   NUMBER(4) NOT NULL
);

CREATE UNIQUE INDEX jc_invoice__idx ON
    jc_invoice (
        order_id
    ASC );

ALTER TABLE jc_invoice ADD CONSTRAINT jc_invoice_pk PRIMARY KEY ( invoice_id );

CREATE TABLE jc_order (
    order_id   NUMBER(4) NOT NULL,
    order_date DATE NOT NULL,
    cust_id    NUMBER(6) NOT NULL,
    invoice_id NUMBER(5) NOT NULL
);

CREATE UNIQUE INDEX jc_order__idx ON
    jc_order (
        invoice_id
    ASC );

ALTER TABLE jc_order ADD CONSTRAINT jc_order_pk PRIMARY KEY ( order_id );

CREATE TABLE jc_product (
    prod_id          NUMBER(5) NOT NULL,
    prod_description VARCHAR2(30) NOT NULL,
    prod_finish      VARCHAR2(30) NOT NULL,
    prod_std_price   FLOAT(8) NOT NULL
);

ALTER TABLE jc_product ADD CONSTRAINT jc_product_pk PRIMARY KEY ( prod_id );

ALTER TABLE jc_cust_order
    ADD CONSTRAINT jc_cust_order_jc_order_fk FOREIGN KEY ( order_id )
        REFERENCES jc_order ( order_id );

ALTER TABLE jc_cust_order
    ADD CONSTRAINT jc_cust_order_jc_product_fk FOREIGN KEY ( prod_id )
        REFERENCES jc_product ( prod_id );

ALTER TABLE jc_invoice
    ADD CONSTRAINT jc_invoice_jc_order_fk FOREIGN KEY ( order_id )
        REFERENCES jc_order ( order_id );

ALTER TABLE jc_order
    ADD CONSTRAINT jc_order_jc_customer_fk FOREIGN KEY ( cust_id )
        REFERENCES jc_customer ( cust_id );

ALTER TABLE jc_order
    ADD CONSTRAINT jc_order_jc_invoice_fk FOREIGN KEY ( invoice_id )
        REFERENCES jc_invoice ( invoice_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             2
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
