-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-11-12 16:52:21 EST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE corporate ( 
--  customer id
    cust_id   NUMBER(5) NOT NULL, 
--  Employee ID of the customer who rents the car on a corporate account
    emp_id    NUMBER(5) NOT NULL, 
--  details of corporation name
    corp_name VARCHAR2(30) NOT NULL, 
--  registration number of the corporation
    reg_no    VARCHAR2(9) NOT NULL
);

COMMENT ON COLUMN corporate.cust_id IS
    'customer id';

COMMENT ON COLUMN corporate.emp_id IS
    'Employee ID of the customer who rents the car on a corporate account';

COMMENT ON COLUMN corporate.corp_name IS
    'details of corporation name';

COMMENT ON COLUMN corporate.reg_no IS
    'registration number of the corporation';

ALTER TABLE corporate ADD CONSTRAINT corporate_pk PRIMARY KEY ( cust_id );

ALTER TABLE corporate ADD CONSTRAINT corporate_pkv1 UNIQUE ( emp_id );

CREATE TABLE discount_corp ( 
--  discount id
    discount_id NUMBER(5) NOT NULL, 
--  percentage of discount offered for corporation
    disc_perc   NUMBER(5, 2) NOT NULL, 
--  corporation name
    corp_name   VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN discount_corp.discount_id IS
    'discount id';

COMMENT ON COLUMN discount_corp.disc_perc IS
    'percentage of discount offered for corporation';

COMMENT ON COLUMN discount_corp.corp_name IS
    'corporation name';

ALTER TABLE discount_corp ADD CONSTRAINT discount_corp_pk PRIMARY KEY ( discount_id );

CREATE TABLE discount_indi ( 
--  discount id
    discount_id NUMBER(5) NOT NULL, 
--  percentage of discount offered for individual
    disc_perc   NUMBER(5, 2) NOT NULL, 
--  discount coupon start date
    start_date  DATE NOT NULL, 
--  discount coupon end date
    end_date    DATE NOT NULL
);

COMMENT ON COLUMN discount_indi.discount_id IS
    'discount id';

COMMENT ON COLUMN discount_indi.disc_perc IS
    'percentage of discount offered for individual';

COMMENT ON COLUMN discount_indi.start_date IS
    'discount coupon start date';

COMMENT ON COLUMN discount_indi.end_date IS
    'discount coupon end date';

ALTER TABLE discount_indi ADD CONSTRAINT discount_indi_pk PRIMARY KEY ( discount_id );

CREATE TABLE individual ( 
--  customer id
    cust_id        NUMBER(5) NOT NULL, 
--   Driver License Number
    drv_license_no VARCHAR2(12) NOT NULL, 
--  Insurance Company Name
    ins_cmp_name   VARCHAR2(30) NOT NULL, 
--  Insurance Policy Number
    ins_pol_no     VARCHAR2(13) NOT NULL
);

COMMENT ON COLUMN individual.cust_id IS
    'customer id';

COMMENT ON COLUMN individual.drv_license_no IS
    ' Driver License Number';

COMMENT ON COLUMN individual.ins_cmp_name IS
    'Insurance Company Name';

COMMENT ON COLUMN individual.ins_pol_no IS
    'Insurance Policy Number';

ALTER TABLE individual ADD CONSTRAINT individual_pk PRIMARY KEY ( cust_id );

ALTER TABLE individual ADD CONSTRAINT individual_pkv1 UNIQUE ( drv_license_no );

CREATE TABLE jc_card_type ( 
--  CARD TYPE ID
    card_type_id NUMBER(5) NOT NULL, 
--  card type name
    type_name    VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN jc_card_type.card_type_id IS
    'CARD TYPE ID';

COMMENT ON COLUMN jc_card_type.type_name IS
    'card type name';

ALTER TABLE jc_card_type ADD CONSTRAINT jc_card_type_pk PRIMARY KEY ( card_type_id );

CREATE TABLE jc_customer ( 
--  customer id
    cust_id    NUMBER(5) NOT NULL, 
--  customer first name
    fname      VARCHAR2(30) NOT NULL, 
--  customer last name
    lname      VARCHAR2(30) NOT NULL, 
--  customer street
    street     VARCHAR2(30) NOT NULL, 
--  customer city
    city       VARCHAR2(20) NOT NULL, 
--  customer state
    state      VARCHAR2(30) NOT NULL, 
--  customer zipcode
    zipcode    VARCHAR2(10) NOT NULL, 
--  customer phone number
    phone_no   VARCHAR2(12) NOT NULL, 
--  customer email
    email      VARCHAR2(50) NOT NULL, 
--  customer type
    cust_type  VARCHAR2(1) NOT NULL, 
--  service_id
    service_id NUMBER(5) NOT NULL
);

ALTER TABLE jc_customer
    ADD CONSTRAINT ch_inh_jc_customer CHECK ( cust_type IN ( 'C', 'I' ) );

COMMENT ON COLUMN jc_customer.cust_id IS
    'customer id';

COMMENT ON COLUMN jc_customer.fname IS
    'customer first name';

COMMENT ON COLUMN jc_customer.lname IS
    'customer last name';

COMMENT ON COLUMN jc_customer.street IS
    'customer street';

COMMENT ON COLUMN jc_customer.city IS
    'customer city';

COMMENT ON COLUMN jc_customer.state IS
    'customer state';

COMMENT ON COLUMN jc_customer.zipcode IS
    'customer zipcode';

COMMENT ON COLUMN jc_customer.phone_no IS
    'customer phone number';

COMMENT ON COLUMN jc_customer.email IS
    'customer email';

COMMENT ON COLUMN jc_customer.cust_type IS
    'customer type';

COMMENT ON COLUMN jc_customer.service_id IS
    'service_id';

ALTER TABLE jc_customer ADD CONSTRAINT jc_customer_pk PRIMARY KEY ( cust_id );

CREATE TABLE jc_discount ( 
--  discount id
    discount_id   NUMBER(5) NOT NULL, 
--  discount type
    discount_type VARCHAR2(1) NOT NULL
);

ALTER TABLE jc_discount
    ADD CONSTRAINT ch_inh_jc_discount CHECK ( discount_type IN ( 'C', 'I' ) );

COMMENT ON COLUMN jc_discount.discount_id IS
    'discount id';

COMMENT ON COLUMN jc_discount.discount_type IS
    'discount type';

ALTER TABLE jc_discount ADD CONSTRAINT jc_discount_pk PRIMARY KEY ( discount_id );

CREATE TABLE jc_invoice ( 
--  Invoice id
    invoice_id     NUMBER(5) NOT NULL, 
--  INVOICE DATE
    invoice_date   DATE NOT NULL, 
--  INVOICE AMOUNT
    invoice_amount NUMBER(7, 2) NOT NULL, 
--  service id
    service_id     NUMBER(5) NOT NULL
);

COMMENT ON COLUMN jc_invoice.invoice_id IS
    'Invoice id';

COMMENT ON COLUMN jc_invoice.invoice_date IS
    'INVOICE DATE';

COMMENT ON COLUMN jc_invoice.invoice_amount IS
    'INVOICE AMOUNT';

COMMENT ON COLUMN jc_invoice.service_id IS
    'service id';

ALTER TABLE jc_invoice ADD CONSTRAINT jc_invoice_pk PRIMARY KEY ( invoice_id );

CREATE TABLE jc_loc ( 
--  office location
    loc_id   NUMBER(4) NOT NULL, 
--  office location street
    street   VARCHAR2(30) NOT NULL, 
--  office location city
    city     VARCHAR2(30) NOT NULL, 
--  location state
    state    VARCHAR2(30) NOT NULL, 
--  office location zipcode
    zipcode  VARCHAR2(10) NOT NULL, 
--  office phone number
    phone_no VARCHAR2(12) NOT NULL
);

COMMENT ON COLUMN jc_loc.loc_id IS
    'office location';

COMMENT ON COLUMN jc_loc.street IS
    'office location street';

COMMENT ON COLUMN jc_loc.city IS
    'office location city';

COMMENT ON COLUMN jc_loc.state IS
    'office location state';

COMMENT ON COLUMN jc_loc.zipcode IS
    'office location zipcode';

COMMENT ON COLUMN jc_loc.phone_no IS
    'office phone number';

ALTER TABLE jc_loc ADD CONSTRAINT jc_loc_pk PRIMARY KEY ( loc_id );

CREATE TABLE jc_payment ( 
--  PAYMENT ID
    payment_id   NUMBER(5) NOT NULL, 
--  PAYMENT DATE
    payment_date DATE NOT NULL, 
--  card number
    card_no      NUMBER(16) NOT NULL, 
--  invoice id
    invoice_id   NUMBER(5) NOT NULL, 
--  card type id
    card_type_id NUMBER(5) NOT NULL
);

COMMENT ON COLUMN jc_payment.payment_id IS
    'PAYMENT ID';

COMMENT ON COLUMN jc_payment.payment_date IS
    'PAYMENT DATE';

COMMENT ON COLUMN jc_payment.card_no IS
    'card number';

COMMENT ON COLUMN jc_payment.invoice_id IS
    'invoice id';

COMMENT ON COLUMN jc_payment.card_type_id IS
    'card type id';

ALTER TABLE jc_payment ADD CONSTRAINT jc_payment_pk PRIMARY KEY ( payment_id );

CREATE TABLE jc_service ( 
--  rent service id
    service_id  NUMBER(5) NOT NULL, 
--  rent service days number
    days_no     NUMBER(2) NOT NULL, 
--  rent service start odometer
    start_odo   NUMBER(6) NOT NULL, 
--  rent service end odometer
    end_odo     NUMBER(6) NOT NULL, 
--  pickup location
    pickup_loc  NUMBER(4) NOT NULL, 
--  dropoff location
    dropoff_loc NUMBER(4) NOT NULL, 
--  discount id
    discount_id NUMBER(5) NOT NULL
);

COMMENT ON COLUMN jc_service.service_id IS
    'rent service id';

COMMENT ON COLUMN jc_service.days_no IS
    'rent service days number';

COMMENT ON COLUMN jc_service.start_odo IS
    'rent service start odometer';

COMMENT ON COLUMN jc_service.end_odo IS
    'rent service end odometer';

COMMENT ON COLUMN jc_service.pickup_loc IS
    'pickup location';

COMMENT ON COLUMN jc_service.dropoff_loc IS
    'dropoff location';

COMMENT ON COLUMN jc_service.discount_id IS
    'discount id';

CREATE UNIQUE INDEX jc_service__idx ON
    jc_service (
        discount_id
    ASC );

ALTER TABLE jc_service ADD CONSTRAINT jc_service_pk PRIMARY KEY ( service_id );

CREATE TABLE jc_vehicle ( 
--  Vehicle Identification Number
    vehicle_vin      VARCHAR2(17) NOT NULL, 
--  VEHICLE MAKE
    vehicle_make     VARCHAR2(30) NOT NULL, 
--  VEHICLE MODEL
    vehicle_model    VARCHAR2(30) NOT NULL, 
--  VEHICLE YEAR
    vehicle_year     NUMBER(4) NOT NULL, 
--  LICENSE PLATE NUMBER
    license_plate_no VARCHAR2(8) NOT NULL, 
--  location id
    loc_id           NUMBER(4) NOT NULL, 
--  vehicle id
    vehicle_id       NUMBER(5) NOT NULL
);

COMMENT ON COLUMN jc_vehicle.vehicle_vin IS
    'Vehicle Identification Number';

COMMENT ON COLUMN jc_vehicle.vehicle_make IS
    'VEHICLE MAKE';

COMMENT ON COLUMN jc_vehicle.vehicle_model IS
    'VEHICLE MODEL';

COMMENT ON COLUMN jc_vehicle.vehicle_year IS
    'VEHICLE YEAR';

COMMENT ON COLUMN jc_vehicle.license_plate_no IS
    'LICENSE PLATE NUMBER';

COMMENT ON COLUMN jc_vehicle.loc_id IS
    'location id';

COMMENT ON COLUMN jc_vehicle.vehicle_id IS
    'vehicle id';

ALTER TABLE jc_vehicle ADD CONSTRAINT jc_vehicle_pk PRIMARY KEY ( vehicle_vin );

CREATE TABLE jc_vehicle_class ( 
--  vehicle class id
    vehicle_id        NUMBER(5) NOT NULL, 
--  vehicle type
    vehicle_type      VARCHAR2(30) NOT NULL, 
--  rental rate per day
    daily_rate        NUMBER(5, 2) NOT NULL, 
--  fees for over mileage per day
    over_mileage_rate NUMBER(4, 2) NOT NULL, 
--  odometer limit
    odo_limit         NUMBER(4) NOT NULL, 
--  service id
    service_id        NUMBER(5) NOT NULL
);

COMMENT ON COLUMN jc_vehicle_class.vehicle_id IS
    'vehicle class id';

COMMENT ON COLUMN jc_vehicle_class.vehicle_type IS
    'vehicle type';

COMMENT ON COLUMN jc_vehicle_class.daily_rate IS
    'rental rate per day';

COMMENT ON COLUMN jc_vehicle_class.over_mileage_rate IS
    'fees for over mileage per day';

COMMENT ON COLUMN jc_vehicle_class.odo_limit IS
    'odometer limit';

COMMENT ON COLUMN jc_vehicle_class.service_id IS
    'service id';

ALTER TABLE jc_vehicle_class ADD CONSTRAINT jc_vehicle_class_pk PRIMARY KEY ( vehicle_id );

ALTER TABLE corporate
    ADD CONSTRAINT corporate_jc_customer_fk FOREIGN KEY ( cust_id )
        REFERENCES jc_customer ( cust_id );

ALTER TABLE discount_corp
    ADD CONSTRAINT discount_corp_jc_discount_fk FOREIGN KEY ( discount_id )
        REFERENCES jc_discount ( discount_id );

ALTER TABLE discount_indi
    ADD CONSTRAINT discount_indi_jc_discount_fk FOREIGN KEY ( discount_id )
        REFERENCES jc_discount ( discount_id );

ALTER TABLE individual
    ADD CONSTRAINT individual_jc_customer_fk FOREIGN KEY ( cust_id )
        REFERENCES jc_customer ( cust_id );

ALTER TABLE jc_customer
    ADD CONSTRAINT jc_customer_jc_service_fk FOREIGN KEY ( service_id )
        REFERENCES jc_service ( service_id );

ALTER TABLE jc_invoice
    ADD CONSTRAINT jc_invoice_jc_service_fk FOREIGN KEY ( service_id )
        REFERENCES jc_service ( service_id );

ALTER TABLE jc_payment
    ADD CONSTRAINT jc_payment_jc_card_type_fk FOREIGN KEY ( card_type_id )
        REFERENCES jc_card_type ( card_type_id );

ALTER TABLE jc_payment
    ADD CONSTRAINT jc_payment_jc_invoice_fk FOREIGN KEY ( invoice_id )
        REFERENCES jc_invoice ( invoice_id );

ALTER TABLE jc_service
    ADD CONSTRAINT jc_service_jc_discount_fk FOREIGN KEY ( discount_id )
        REFERENCES jc_discount ( discount_id );

ALTER TABLE jc_service
    ADD CONSTRAINT jc_service_jc_loc_fk FOREIGN KEY ( pickup_loc )
        REFERENCES jc_loc ( loc_id );

ALTER TABLE jc_service
    ADD CONSTRAINT jc_service_jc_loc_fkv2 FOREIGN KEY ( dropoff_loc )
        REFERENCES jc_loc ( loc_id );

ALTER TABLE jc_vehicle_class
    ADD CONSTRAINT jc_vehicle_class_jc_service_fk FOREIGN KEY ( service_id )
        REFERENCES jc_service ( service_id );

ALTER TABLE jc_vehicle
    ADD CONSTRAINT jc_vehicle_jc_loc_fk FOREIGN KEY ( loc_id )
        REFERENCES jc_loc ( loc_id );

ALTER TABLE jc_vehicle
    ADD CONSTRAINT jc_vehicle_jc_vehicle_class_fk FOREIGN KEY ( vehicle_id )
        REFERENCES jc_vehicle_class ( vehicle_id );

CREATE OR REPLACE TRIGGER arc_fkarc_4_corporate BEFORE
    INSERT OR UPDATE OF cust_id ON corporate
    FOR EACH ROW
DECLARE
    d VARCHAR2(1);
BEGIN
    SELECT
        a.cust_type
    INTO d
    FROM
        jc_customer a
    WHERE
        a.cust_id = :new.cust_id;

    IF ( d IS NULL OR d <> 'C' ) THEN
        raise_application_error(-20223, 'FK CORPORATE_JC_CUSTOMER_FK in Table CORPORATE violates Arc constraint on Table JC_CUSTOMER - discriminator column CUST_TYPE doesn''t have value ''C'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_4_individual BEFORE
    INSERT OR UPDATE OF cust_id ON individual
    FOR EACH ROW
DECLARE
    d VARCHAR2(1);
BEGIN
    SELECT
        a.cust_type
    INTO d
    FROM
        jc_customer a
    WHERE
        a.cust_id = :new.cust_id;

    IF ( d IS NULL OR d <> 'I' ) THEN
        raise_application_error(-20223, 'FK INDIVIDUAL_JC_CUSTOMER_FK in Table INDIVIDUAL violates Arc constraint on Table JC_CUSTOMER - discriminator column CUST_TYPE doesn''t have value ''I'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_5_discount_indi BEFORE
    INSERT OR UPDATE OF discount_id ON discount_indi
    FOR EACH ROW
DECLARE
    d VARCHAR2(1);
BEGIN
    SELECT
        a.discount_type
    INTO d
    FROM
        jc_discount a
    WHERE
        a.discount_id = :new.discount_id;

    IF ( d IS NULL OR d <> 'I' ) THEN
        raise_application_error(-20223, 'FK DISCOUNT_INDI_JC_DISCOUNT_FK in Table DISCOUNT_INDI violates Arc constraint on Table JC_DISCOUNT - discriminator column DISCOUNT_TYPE doesn''t have value ''I'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_5_discount_corp BEFORE
    INSERT OR UPDATE OF discount_id ON discount_corp
    FOR EACH ROW
DECLARE
    d VARCHAR2(1);
BEGIN
    SELECT
        a.discount_type
    INTO d
    FROM
        jc_discount a
    WHERE
        a.discount_id = :new.discount_id;

    IF ( d IS NULL OR d <> 'C' ) THEN
        raise_application_error(-20223, 'FK DISCOUNT_CORP_JC_DISCOUNT_FK in Table DISCOUNT_CORP violates Arc constraint on Table JC_DISCOUNT - discriminator column DISCOUNT_TYPE doesn''t have value ''C'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             1
-- ALTER TABLE                             31
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           4
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
